app:
  config:
    rest:
      connect-timeout: 15000
      connection-request-timeout: 15000
      socket-timeout: 15000
      max-conn-per-route: 5
      max-conn-total: 5

server:
  port: 8083
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    hikari:
      idle-timeout: 300000
      keepalive-time: 590000
      max-lifetime: 600000
      maximum-pool-size: 10
      minimum-idle: 0
    password: postgres
    url: jdbc:postgresql://localhost:5432/db_order_service
    username: postgres
    driver-class-name: org.postgresql.Driver

logging:
  file:
    name: order-service.log
  pattern:
    file: '{''app'':''order-service'',''datetime'': ''%d{yyyy-MM-dd HH:mm:ss}'',
            ''thread'': ''%thread'', ''level'': ''%-5level'', ''logger'': ''%logger{36}'', ''item'':''%msg''}%n'

springdoc:
  swagger-ui:
    path: /swagger/index.html
    enabled: true

integration:
  product-service:
    url: http://product-service:8081/product-service/api/v1
  payment-service:
    url: http://payment-service:8082/payment-service/api/v1